name: Push

on:
  push:
    branches:
      - main

jobs:
  test-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test GitHub auth
        run: echo $ACTIONS_ID_TOKEN_REQUEST_TOKEN | base64 | base64
